name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev git zip unzip openjdk-17-jdk
          sudo pip3 install buildozer cython

      - name: Build APK
        run: |
          yes | buildozer android debug deploy run

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lastchance-2.1
          path: bin/*.apk
